print('Hello world! \nWhat is your name?')
myName = input()
print('Its good to meet you '+myName+'. \nThe length of your name is')
print(len(myName))
print('How old are you?')
age = input()
print('You will be '+str(int(age)+1)+' in one year')
